### ISSUE TITLE
player.isPlaying() raises segfault

### ISSUE THREAD

**Issue by asdil12** [sdroege/gst-player#7] opened 2014-08-22 10:11 UTC
```
08-22 11:55:06.827  24078-24078/de.f3l.abook A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 24078 (de.f3l.abook)
```

**Comment by sdroege** [comment] 2015-02-08 10:42
Closing as I can't reproduce this here and no further information was provided in the last few months.

**Closed by sdroege** 2015-02-08 10:42 UTC
